### ISSUE TITLE
Bug in Sinc Interpolator

### ISSUE THREAD

**Issue by 0xcaff** [RustAudio/sample#106]
I believe I've found a bug in the `Sinc` interpolate. When calling interpolate with `x` = 0.0, `NaN` is returned. Is this intended?

**Comment by est31** [comment]
Sinc is defined by `sin(x)/x`. For x == 0 you have `0/0` which is obviously a problem and most likely the source of that. Usually people define the value of sinc to be 1 at that position, as it's the value that the function converges to at this location (from both directions).

**Comment by est31** [comment]
So yeah, I guess that's a bug.
