### ISSUE TITLE
ring_buffer not included in hosted docs

### ISSUE THREAD

**Issue by willstott101** [RustAudio/sample#115]
I can't find any docs for the Ring Buffer implementation on your github.io site. But if I generate the docs locally with `cargo doc` they're included.

**Comment by est31** [comment]
@willstott101 thanks for the report. You are likely visiting an outdated version of sample, as the official docs are on docs.rs and they [do contain ring_buffer](https://docs.rs/sample/0.10.0/sample/ring_buffer/index.html). Could you provide a link to that github.io site? Maybe we could ask the owner to remove it.

**Comment by willstott101** [comment]
Ahah, thanks for pointing me to the right place.

I'm not sure how I got to: http://rustaudio.github.io/sample/sample/index.html (probably via a search engine), I was surprised that you weren't using docs.rs, good to see you are :)

**Comment by est31** [comment]
Alright I have disabled github pages for this repository by deleting the gh-pages branch (couldn't find another way). Thanks for the report!
