### ISSUE TITLE
Add no_std option

### ISSUE THREAD

**Issue by cmr** [RustAudio/sample#24]
You claim "no dependencies", but std is actually a quite large dependency in some environments. Most of this crate can do without `std` and use only `core` (ie, function overloading traits)`.

There's a few bits which can't: 

- `Rc` https://github.com/RustAudio/sample/blob/4a4c679268605e539342f52b702a21189534526a/src/signal.rs#L581
- `Vec` and `VecDeque` https://github.com/RustAudio/sample/blob/4a4c679268605e539342f52b702a21189534526a/src/signal.rs#L590
- `Rc` https://github.com/RustAudio/sample/blob/4a4c679268605e539342f52b702a21189534526a/src/signal.rs#L601

It's a bit unfortunate trying to use `alloc` and `collections`, as they are currently unstable. I recommend adding a `no_std` feature that explicitly depends on those crates, with internal aliases for `Rc`, `Vec`, and `VecDeque` that switch between `std` and `alloc`/`collections` based on `#[cfg(feature = "no_std")]`. This does imply that `no_std` is unstable.

If you're happy with this, I can send a PR doing these changes.

**Comment by mitchmindtree** [comment]
@cmr that would be amazing!

I'm pretty sure that `Rc`, `Vec` and `VecDeque` are only used as a part of the `Signal::bus` method. I'd actually be more than happy to make a stable, `no_std` the default, and have a `bus` feature which would enable the `Signal::bus` method, the related `Bus`, `Output` and `SharedNode` types and necessary alloc and collections deps. What are your thoughts?

**Comment by cmr** [comment]
That thought occured to me, but the `Signal::bus` functionality seems pretty essential to me, in that it's how arbitrary DSP graphs can be composed. I'm just a novice in this particular field, but that seems important to me for most consumers.  Your call!

**Comment by mitchmindtree** [comment]
Yeah the more I think about it I think you're right, I like your `no_std` feature idea best. It's a pity that `no_std` would require unstable, but understandable and better than no `no_std` at all.

Are you aware of whether or not `alloc` and `collections` might be stable soon? Or is it a "probably not going to happen for a while" thing?

Either way, I'd be more than happy to go with your suggestion :+1:

**Comment by cmr** [comment]
I don't know, but I suspect it won't be for a while.
