### ISSUE TITLE
Add Window Iterators

### ISSUE THREAD

**Issue by andrewcsmith** [RustAudio/sample#32]
After [our brief discussion on /r/rust](https://www.reddit.com/r/rust/comments/4arjm8/sample_050_the_fundamentals_for_working_with/d13grzb), I thought that now is the time to move my `Window` functions to your `sample` crate. I'm having a hard time conceptualizing where to put this though. It seems like `sample` is focused on the time domain, and (in general) windowing is mostly used in the frequency domain. 

Here's a limited, first-steps proposal:

* Implement `Window` as a `struct` implementing `Iterator`
* `Window` will yield `Frame`s, allowing for a trivial impl of `Signal`
* `Window` can be instantiated with a convenience function similar to `signal::sine` or `signal::saw`, with an argument of an `Iterator` that yields a `Phase`
* Users can then call `mul_amp` on their own time to multiply the two signals

This is pretty simple. The catch is that this wouldn't actually implement *windowing* but only common window functions like Hanning/Hamming/Rectangular/etc. represented as oscillators.

Step two would be to implement a sliding window that (given a bin and hop) yields up slices of `Frame`s. I believe this should be an `Iterator` called `Windower` where:

```rust
// WARNING: I haven't actually tried to compile any of this. Pseudo.
struct Windower<'a, F> {
    window: Window<F>,
    current_index: usize,
    hop: usize,
    input: &'a [F],
    data: &'a mut [F]
}

impl<'a, T: ToFrameSliceMut<'a, F>, F: Frame> Windower<'a, F> {
    fn new<'a>(type: WindowType, input: &'a [F], data_store: &'a mut [F]) -> Windower<'a, F> {
        // Create a `Window`-type `Signal` as outlined above, taking the `Phase` 
        // frequency from data_store.len()
    }
}

impl<'a, F: Frame> Iterator for Windower<'a, F> {
    type Item = &[F];
    fn next(&mut self) -> Self::Item {
        // update self.data with the product of the window value and input[(self.current_index*self.hop)..(self.current_index*self.hop+self.data.len())]
        // increment current_index by hop. (the bin is inferred from the size of self.data)
        // yield the value of self.data as an immutable reference
    }
}
```

This way, the `Windower` would be an iterator that would yield immutable slices of `Frame`s.

Let me know if this looks like an all right implementation. I'm not quite sure what the state of spectral analysis in the `sample` crate is going to be, but it would be fantastic to at least have many of these functions be generalized over `Sample` and `Frame`.

**Comment by mitchmindtree** [comment]
This all sounds great @andrewcsmith :smile_cat: perhaps Window and Windower could be implemented in a `window` module? We could either add a convenience function to the signal module like you mentioned, or perhaps instead we could make constructor functions in the `window` module, i.e. `sample::window::hanning`?

> It seems like sample is focused on the time domain...

I'm absolutely interested in providing more frequency domain oriented functionality to sample, but figured it was important to get the time domain right first (which I think is at a pretty good place now with `Frame` and `Signal`). On a slightly related note, I think a pure-rust non-allocating fft would be really nice, and we could also use some higher quality interpolation types for `rate::Converter` (at the moment there is only linear). I might add separate issues for those.

**Comment by andrewcsmith** [comment]
Great. I see this as a first step to getting some frequency domain functionality. I'll work in a module, and look into step 1 asap.

**Comment by andrewcsmith** [comment]
Okay, sorry it's been a while. I have an initial draft of what I'm thinking. Could you look it over and let me know if I'm:

1. Making things as general as possible
2. Adhering to the idiomatic conventions of the crate

I decided on using empty structs instead of an enum to hold the `WindowType`. This will allow for static dispatch and minimal branches in the compiled code. Currently, `Window` is basically just another oscillator. I kind of like this as it allows us to reuse the same `Window`.

I haven't actually used the `sample` crate myself (although I hope to soon) so give this a look and let me know if there's anything I'm missing about the design of the crate. It's not ready for a PR yet. 

https://github.com/andrewcsmith/sample/commit/216f3c44782d82b6005ea9c2506143cc1d3a0c0b

**Comment by andrewcsmith** [comment]
A couple more changes (I'm on a roll). It's a rat's nest of generic programming and 👻`PhantomData`👻 but I'm happy with how this is turning out. It borrows a slice, and then yields iterators of iterators of `Frame`s, looping through the window for each one. There are [a couple tests](https://github.com/andrewcsmith/sample/blob/master/tests/window.rs) as examples.

My favorite part about this is that it doesn't use enums or trait objects in any way, has no dynamic allocations, and (should do) all the necessary type checking at compile-time.

**Comment by mitchmindtree** [comment]
Hey @andrewcsmith, looking great, definitely appreciate moving the enum variants into their own types! There are a few things that I want to leave comments about, I should be able to later today but feel free to open a PR in the meantime as it'll make it even easier to leave comments inline :) If not, I'll just link to the line numbers here later on :+1:

**Comment by andrewcsmith** [comment]
PR created. Yes, it's not quite there yet. Interested to see you comments—it would be nice, I think, to have a clear example of how to reuse the Window functions as lookup tables, rather than calculating them new each time. In this instance I went for elegance and zero allocations over computational efficiency, but it would be nice to have either option.

**Comment by andrewcsmith** [comment]
Can we close this one? I think windows are pretty okay. There are some additional functions I might want to implement, but for now this is actually working very well for my purposes. (I should probably write an example, tbqh, but that can be a different issue.)
