### ISSUE TITLE
The `Signal` trait should return `Self::Frame` rather than `Option<Self::Item>`

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/sample#54]
Currently the `Signal` trait depends on the `Iterator<Item=F>` trait (where F is some `Frame` type).

While this is really convenient in terms of implementation (every Iterator that returns a `Frame` type automatically implements `Signal`), the `Option` around the `next` method return type does not really make sense.

Most signals are infinite/continuous (e.g. periodic waveforms like sine, square, noise, etc) and the `Option` is an unnecessary hinderance and in some cases a performance hit. Even for finite-length sample playback, it would probably feel more natural for the signal to return silence rather than `None`.

I think the crate would benefit from reworking the `Signal` trait so that it did not require `Iterator` and instead provided its own `next` method that returned an associated `Frame` type.

For convenience, we *could* could add a signal adaptor type that converted an `Iterator<Item=F>` into a `Signal<Frame=F>`, where the `None` case for the `Iterator` returns `F::equilibrium`.

cc @andrewcsmith

**Comment by andrewcsmith** [comment]
Likewise, we can add `Signal impl IntoIterator<F>`. This should make for a fairly minimally breaking change.

**Comment by tuxmark5** [comment]
This change is extremely disappointing. I've recently upgraded to the newest version of the library and found that this change completely breaks my codebase.

I've been using sample crate to resample and adjust the volume of a vorbis stream that is being decoded in real-time. After a single vorbis stream is finished, another is started immediately. This worked great in the past, as I could know when the resampled stream ends (as the iterator would return None indicating end of the stream). But now this is no longer possible. The example resample.rs works around this by knowing the exact amount of samples in the source beforehand - but in my case this is impossible as the vorbis file is streamed from internet and decoded live. Therefore there is no way to know how many samples are there in the source, as such it's impossible to calculate the resampled amount of samples.

I would love to hear any possible suggestions as how to migrate to the new Signal and how to detect end of the stream when the source length cannot be predicted or estimated beforehand.

**Comment by andrewcsmith** [comment]
I hear you. The removal of any checks is a significant performance boost, though, for something that's such a common use-case. Just checking a drop flag is a performance hit, and this library (as I understand it) aims to eliminate basically all possible runtime performance penalties.

I do think that "stream that ends" is an abstraction over "stream that never ends," in that they both really don't ever end, except that one eventually just returns `None` (but of course returning `None` is still returning _something_).

@mitchmindtree: What would be the possibilities to writing `Frame` so that we could `impl Frame for Option<impl Frame>`? Seems that would solve this problem, and would allow people to take the performance hit if they want to know when the stream ends. We're overdue to look into `Frame` anyway, given that associated consts have landed in stable.

@tuxmark5: if you can post a gist or some example code it might be easier to help you with your particular problem. I just recently converted a pile of code (some of it real-time) to use the new API and am willing to take a lot.

**Comment by tuxmark5** [comment]
@andrewcsmith Here's the problematic code fragment:
https://gist.github.com/tuxmark5/4b460d1dd58ad6da2c147faea0f7aee0

Decoder there is a Vorbis decoder that decodes things live from a stream that is being downloaded.

**Comment by mitchmindtree** [comment]
@tuxmark5 I totally understand where you're coming from, I remember this crossing my mind briefly while making the change but deciding that we'd be better off working out some better, separate abstraction for exhaustive signals - I should have added an issue at the time, thanks for bringing this up!

@andrewcsmith yeah I totally agree that exhaustive signals are a subset of infinite signals in that sense. I'm not sure if rust's type system is fancy enough to allow us to express this nicely in the Signal trait alone though 🤔 Perhaps we could create another signal adapter like `signal::from_iter` that sets some flag once the iterator starts yielding `None` so that the user can check it? I'm not sure what the easiest way of accessing this flag would be though. Will have to give this some more thought.

On the topic of using a flag, @tuxmark5 perhaps something like this could get you by for now? E.g. wrapping your `src` sample iterator in an adaptor that sets a `&Cell<bool>` that you have local access to to `true` when the `Iterator` returns `None`. Something along these lines

```rust
let is_exhausted = Cell::new(false); // A flag that gets set to true by ExhaustiveCheck when iter returns None.
let mut iter = ExhaustiveCheck::new(src, &is_exhausted);
let signal = signal::from_interleaved_samples_iter(iter);
let interpolator = Linear::from_source(&mut signal);
let dst_signal = signal.from_hz_to_hz(interpolator, src_hz, 48_000.0f64);
while !is_exhausted.get() {
    let frame = dst_signal.next();
    // ...
}
```

If you wanted to return an `impl Iterator` as in your example, you could move the `while` loop iteration into some new Iterator type (though this might require putting the Cell in an Rc so it could be moved into this new iterator type). Definitely not as nice as the old setup, but maybe something like this can get you by for now?

> What would be the possibilities to writing Frame so that we could impl Frame for Option<impl Frame>?

@andrewcsmith Hmmm possibly, though treating an Option<Frame> like a regular Frame feels a little hackish to me. I feel like addressing this at the signal level with some sort of adaptor or something might be a better option. That said I'm not really sure yet!

> We're overdue to look into Frame anyway, given that associated consts have landed in stable.

I had a go at this once it stabilised a couple weeks back however there was a bug at the time that disallowed the use  of associated consts as sizes for fixed size arrays (which is almost the sole purpose I want them 😕 ). Might have been fixed by now though, could be worth looking into again.

**Comment by tuxmark5** [comment]
@mitchmindtree Thank you for the tip. I've already constructed a similar workaround by creating a custom exhaustion iterator that I chain() to the source iterator, that marks a Rc<Cell<bool>> when the source stream becomes exhausted. At which point I just take_while the resulting stream samples until the flag becomes set.

**Comment by tuxmark5** [comment]
@mitchmindtree Thank you for the patch.
