### ISSUE TITLE
Ring Buffer type

### ISSUE THREAD

**Issue by andrewcsmith** [RustAudio/sample#56]
It would be great to make our own ring buffer (basically, something like `VecDeque`) that uses a `<F: Frame> &mut [F]` in its constructor. (It's impossible to do this with `VecDeque`. I would consider this a 1.0 milestone feature for being able to pitch this library.

**Comment by andrewcsmith** [comment]
What about abstracting the ring buffer functionality into a trait, so people can use a `VecDeque` if they so prefer, or they can go the definitely-zero-allocation route? Thinking of something like this:

```rust
trait RingBuffer<T> {
    fn push(&mut self, a: T);
    fn pop(&mut self) -> T;
}

struct FixedRingBuffer<T> {
    data: &mut [T],
    head: usize,
    tail: usize
}

impl RingBuffer<T> for VecDeque<T> {
    ...
}

impl RingBuffer<T> for FixedRingBuffer<T> {
    ...
}
```

Obviously then `push` could never fail, so `FixedRingBuffer` would have to decide whether to drop the new frame or to cycle and drop the previous frame.

**Comment by mitchmindtree** [comment]
I've been putting some thought into this today and agree it would be very useful. I think it would be great if we could provide some `Buffered<S>` `Signal` adaptor that could use some given `RingBuffer` to buffer groups of frames at a time from the inner `Signal`.

I agree it would be nice if this abstraction was provided for multiple types, these come to mind:

- `VecDeque`
- Owned fixed-size arrays
- `Box`ed slices
- Borrowed slices

It looks like I'll need something like this soon in a project I'm currently working on, so will keep thinking about this and hopefully have a go at it soon.

> so FixedRingBuffer would have to decide whether to drop the new frame or to cycle and drop the previous frame.

True, it would be nice if the user could decide on this behaviour, perhaps via some type param on the buffer (maybe we could settle on some default to improve ergonomics for people who don't care).

**Comment by mitchmindtree** [comment]
Just wanted to mention that I've made a pretty thorough start on this over the past couple of hours and will likely open a PR tonight :+1:
